name: thedang
version: stable
version-script: git -C parts/thedang/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
    The Dang tries to match a rule for the previous command,
    creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
    thedang:
        command: bin/thedang
        environment:
            PYTHONIOENCODING: utf-8
    dang:
        command: bin/dang
        environment:
            PYTHONIOENCODING: utf-8

parts:
    thedang:
        source: https://github.com/nvbn/thedang.git
        plugin: python
